name = "the-cosy-nook-landingpage"
compatibility_date = "2026-07-15"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "SUBSCRIBE_RATE_LIMIT"
id = "replace-with-production-kv-namespace-id"
preview_id = "replace-with-preview-kv-namespace-id"
